/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortofoliuRouteImport } from './routes/portofoliu'
import { Route as PortofoliuSlugRouteImport } from './routes/portofoliu.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofoliuRoute = PortofoliuRouteImport.update({
  id: '/portofoliu',
  path: '/portofoliu',
  getParentRoute: () => rootRouteImport,
} as any)
const PortofoliuSlugRoute = PortofoliuSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortofoliuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portofoliu': typeof PortofoliuRouteWithChildren
  '/portofoliu/$slug': typeof PortofoliuSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portofoliu': typeof PortofoliuRouteWithChildren
  '/portofoliu/$slug': typeof PortofoliuSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portofoliu': typeof PortofoliuRouteWithChildren
  '/portofoliu/$slug': typeof PortofoliuSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/portofoliu' | '/portofoliu/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/portofoliu' | '/portofoliu/$slug'
  id: '__root__' | '/' | '/contact' | '/portofoliu' | '/portofoliu/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PortofoliuRoute: typeof PortofoliuRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofoliu': {
      id: '/portofoliu'
      path: '/portofoliu'
      fullPath: '/portofoliu'
      preLoaderRoute: typeof PortofoliuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portofoliu/$slug': {
      id: '/portofoliu/$slug'
      path: '/$slug'
      fullPath: '/portofoliu/$slug'
      preLoaderRoute: typeof PortofoliuSlugRouteImport
      parentRoute: typeof PortofoliuRoute
    }
  }
}

interface PortofoliuRouteChildren {
  PortofoliuSlugRoute: typeof PortofoliuSlugRoute
}

const PortofoliuRouteChildren: PortofoliuRouteChildren = {
  PortofoliuSlugRoute: PortofoliuSlugRoute,
}

const PortofoliuRouteWithChildren = PortofoliuRoute._addFileChildren(
  PortofoliuRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PortofoliuRoute: PortofoliuRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
